import type { NextPage } from "next";
import Head from "next/head";
import HeroHome from "../components/partials/HeroHome";
import FeaturesHome from "../components/partials/Features";
import FeaturesBlocks from "../components/partials/FeaturesBlocks";
import Testimonials from "../components/partials/Testimonials";
import CallToAction from "../components/partials/CallToAction";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Outsourced People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroHome />
      <FeaturesHome />
      <CallToAction />
    </>
  );
};

export default Home;
